### ISSUE TITLE
"Further information and documentation can be found in the ./Documents  folder"

### ISSUE THREAD

**Issue by tnull** [tbaumeist/FreeNet-Analysis#1]
Hello,
multiple parts of the READMEs point to this Document folder. 
However, it doesn't exist. Where can I find more information on running a Freenet testbed?

**Comment by tbaumeist** [comment]
Hi,
I have added the documents back into the /Documents directory. Note that the documents are slightly out of date from the current structure. If you can't find a file mentioned in one of the documents, try looking in one of the Archived folders throughout the repo. Also note that the version of Freenet I tooled to record routing information is several years old now.
